# Lecture 3

## Question One Solution

In [1]:
def addListElements(l):
    total = 0
    for elem in l:
        total+=elem
    return total

numbers = [45, 76, -23, 90, 15]

addListElements(numbers)

203

## Question Two Solution

In [ ]:
words = ["the","cat","sat","on","the","mat"]
counts = {}

for word in words:
    if word in counts.keys():
        counts[word] += 1
    else:
        counts[word] = 1
print(counts)

## File Reading

In [ ]:
f = open("data.txt",'r')
for line in f:
    print(line)

Only reads a line

In [ ]:
f = open("data.txt",'r')
print(f.readline())

Reads all lines and stores them in a list

In [ ]:
f = open("data.txt",'r')
print(f.readlines())

## File Reading "with"
The **“with”** statement closes the file automatically. A more
Pythonic implementation.

In [ ]:
with open("data.txt",'r') as f:
    for line in f:
        print(f)

File Writing with the **"w"** attribute.

In [ ]:
words = ["line one","line two","line three","line four"]
with open("data1.txt", "w")as f:
    for word in words:
        f.write(word+'\n')

## Reading a **CSV** file.

In [ ]:
import csv
with open("data.csv", "r") as f:
    reader = csv.reader(f)
    for row in reader:
       print(row)

## Writing a **CSV** File.

In [ ]:
import csv
input_file = open("data.csv", 'r')
reader = csv.reader(input_file)
output_file = open("test_write.csv",'w')
writer = csv.writer(output_file , delimiter=" ",quotechar=' ')
for row in reader:
    writer.writerow(row)
input_file.close()
output_file.close()

Lists are OK for small one dimensional data but not good for **arithmatic operations (+,-,*,..)**.

In [ ]:
a = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
b = [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
print(b[0])
print(b[1][2:4])
c=a+b
print(c)

## Creating Arrays
To create a Numpy array of all **zeros** we can use Numpy's **zeros()** function.

In [ ]:
import numpy as np
a=np.zeros(3)
a

let's use the function **type()** to obtain the data type.

In [ ]:
type(a)

Arrays can also be created by list or tuples. More on arrays can be found here https://docs.python.org/3/library/array.html

In [ ]:
a=np.array([1,2,3,4,5])
a

The numpy function **ones()** can create an array with all ones.

In [ ]:
a = np.ones(3)
b = np.ones([3,3])
print("output for a:", a)
print("output for b:", b)

The nupmy function for **empty()** creates a quick array with random values, by executing the cell a few times you will not the values change.

In [ ]:
d=np.empty([2,2],dtype=int)
d

In our previous example we tried adding to list together, with them only being concatenated. In this next example we will create a Numpy array to see what our results will be.

In [ ]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[1,2,3],[3,4,5]])
c=a+b
print(c)

The numpy function **arange()** is similar to the funtion **range()**.

In [ ]:
q = np.arange(5)
q

## Creating Arrays
The numpy function **linspace()** can generate equal spaced elements. In this example our start range is 1 and our finish range is 10, with three equally space values. Experiment with other values.

In [ ]:
import numpy as np
a = np.linspace(1,10,3)
a

A 2D array example.

In [ ]:
import numpy as np
z = np.array([[1,2],[4,5]])
z

To find out the shape of this array we can use the **shape** function.

In [ ]:
z.shape

In [ ]:
print(np.shape(z))

## Array Indexing
Elements of arrays are accessed using **[ ]** brackets.

In [ ]:
import numpy as np
z = np.linspace(1,2,5)
z

For flat arrays indexing is the same as Python sequences.

In [ ]:
z[0]

In [ ]:
z[0:2]

In [ ]:
z[-1]

## 2d Indexing
Lets look at an example of 2D array.

In [ ]:
import numpy as np
l = np.array([[1,2],[3,4]])
l[0,0]

In [ ]:
l[1,1]

In [ ]:
l[1][1]

In [ ]:
l[0,:]

## Array I/O

In [ ]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
np.savetxt(fname="mydata.txt", X=arr, fmt="%d")
loaded_arr = np.loadtxt(fname="mydata.txt")

## Reshaping Arrays

In [ ]:
import numpy as np
a = np.arange(6) # 1d array
a

In [ ]:
# reshape the array
b = np.arange(6).reshape(3, 2) # 2d array
b

In [ ]:
import numpy as np
c = np.arange(24).reshape(2, 3, 4)
c

## Array Attributes

In [ ]:
arr.ndim

In [ ]:
arr.shape

In [ ]:
arr.size

In [ ]:
arr.dtype

## Array Methods

In [ ]:
s1 = np.arange(6)
s1

In [ ]:
s2=s1.astype(float)
s2

In [ ]:
s3=s2.copy()
s3

In [ ]:
s2[2]=73.88

In [ ]:
s2

In [ ]:
s3

In [ ]:
a=np.array([4,3,2,1])
a.sort()
a

In [ ]:
print(a.sum())


In [ ]:
print(a.mean())

In [ ]:
print(a.min())

In [ ]:
print(a.max())

In [ ]:
print(a.argmax())

In [ ]:
print(a.cumsum())

In [ ]:
print(a.cumprod())

In [ ]:
print(a.var())

In [ ]:
print(a.std())

In [ ]:
print(a.transpose())

In [ ]:
test = np.linspace(2, 4, 5)
print(test)

In [ ]:
test.searchsorted(2.2)

In [ ]:
test.searchsorted(2.5)

In [ ]:
test.searchsorted(2.6)

In [ ]:
a=np.random.rand(3,2)
a

## Array Methods - Random Numbers

In [ ]:
a = np.random.randint(2, size=10)
a

## Array Operationg: Algebraic

In [ ]:
v1 = np.arange(0.6, 1.6, 0.1)
print(v1)

In [ ]:
v2 = np.arange(40.0, 50.0, 1.0)
print(v2)

In [ ]:
print(v1+v2)

In [ ]:
print(v1*v2)

In [ ]:
print(v1-v2)

In [ ]:
print(v1**2)

In [ ]:
print(v1)

In [ ]:
print(v1+0.4)

In [ ]:
print(v1*10)

In [ ]:
print(v1*10+100)

## Array Operations 2D

In [ ]:
A = np.ones((2,2))
B = np.ones((2,2))

In [ ]:
A+B

In [ ]:
A*10

In [ ]:
A*B

## Matrix dot and cross product

In [ ]:
a1 = np.array([[1, 2, -4], [3, -1, 5]])
a2 = np.array([[6, -3], [1, -2], [2, 4]])
a3 = np.array([[3, 3, 2], [7, 8 ,8]])
print(a1)

In [ ]:
print(a2)

In [ ]:
np.dot(a1,a2)

In [ ]:
np.cross(a1,a3)

## Vectorized/ufuncs

In [ ]:
z = np.array([1, 2, 3])
np.sin(z)

In [2]:
import numpy as np
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

In [3]:
### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

elementwise multiplication = [81.  4. 10.  0.  0. 63. 10.  0.  0.  0. 81.  4. 25.  0.  0.]
 ----- Computation time = 0.3740000000000965ms


In [4]:
### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]
 ----- Computation time = 0.21800000000005149ms


## Comparisons

In [5]:
z = np.array([2, 3])
y = np.array([2, 3])
z == y

array([ True,  True])

In [7]:
y[0] = 5
y

array([5, 3])

In [8]:
z == y

array([False,  True])

In [9]:
z != y

array([ True, False])

## Linear Algebra

In [10]:
m = np.array(((2,3), (-1, -2)))

In [11]:
print(m)

[[ 2  3]
 [-1 -2]]


In [12]:
print (np.linalg.det(m))

-1.0


In [13]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
x

array([2., 3.])